import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import { beforeEach, expect, it, vi } from "vitest";
import AppRoutes from "./routes";
const auth = vi.hoisted(() => ({ isGuest: false, accountType: "full_time" }));
vi.mock("./AuthContext", () => ({ useAuth: () => auth }));
vi.mock("../shared/pages/ForgotPassword/ForgotPassword.component", () => ({ default: () => <p>ForgotPasswordPage</p> }));
vi.mock("../shared/pages/ResetPassword/ResetPassword.component", () => ({ default: () => <p>ResetPasswordPage</p> }));
vi.mock("../features/instructor/PrintPlans/PrintPlans.component", () => ({ default: () => <p>PrintPlans</p> }));
vi.mock("../features/instructor/ActivityLibrary/ActivityLibrary.component", () => ({ default: () => <p>ActivityLibrary</p> }));
vi.mock("../features/instructor/LessonPlans/LessonPlans.component", () => ({ default: () => <p>LessonPlans</p> }));
vi.mock("../features/instructor/InstructorHome/InstructorHome.component", () => ({ default: () => <p>InstructorHome</p> }));
vi.mock("../features/instructor/MyClasses/MyClasses.component", () => ({ default: () => <p>MyClasses</p> }));
vi.mock("../features/instructor/Attendance/Attendance.component", () => ({ default: () => <p>InstructorPlaceholder</p> }));
vi.mock("../features/decksupervisor/Dashboard/Dashboard.component", () => ({ default: () => <p>DashboardPage</p> }));
vi.mock("../features/decksupervisor/ManageSessions/ManageSessions.component", () => ({ default: () => <p>ManageSessionsPage</p> }));
vi.mock("../features/decksupervisor/DeviceExport/DeviceExport.component", () => ({ default: () => <p>DeviceExportPage</p> }));
vi.mock("../features/decksupervisor/Print/Print.component", () => ({ default: () => <p>PrintPage</p> }));
vi.mock("../features/decksupervisor/Rosters/Rosters.component", () => ({ default: () => <p>RostersPage</p> }));
vi.mock("../features/decksupervisor/Schematic/Schematic.component", () => ({ default: () => <p>SchematicPage</p> }));
vi.mock("../features/decksupervisor/ReportCards/ReportCards.component", () => ({ default: () => <p>ReportCardsPage</p> }));
vi.mock("../features/decksupervisor/StaffNotes/StaffNotes.component", () => ({ default: () => <p>StaffNotesPage</p> }));
vi.mock("../features/decksupervisor/FullTimerTools/FullTimerTools.component", () => ({ default: () => <p>FullTimerToolsPage</p> }));
vi.mock("../features/decksupervisor/Requests/Requests.component", () => ({ default: () => <p>RequestsPage</p> }));
vi.mock("../shared/pages/SignIn/SignIn.component", () => ({ default: () => <p>SignInPage</p> }));
vi.mock("../shared/pages/Account/Account.component", () => ({ default: () => <p>AccountPage</p> }));
vi.mock("../features/decksupervisor/Team/Team.component", () => ({ default: () => <p>TeamPage</p> }));
vi.mock("../features/decksupervisor/SessionPlanning/SessionPlanning.component", () => ({ default: () => <p>SessionPlanningPage</p> }));
beforeEach(() => { auth.isGuest = false; auth.accountType = "full_time"; });
function setup(url: string) { render(<MemoryRouter initialEntries={[url]}><AppRoutes /></MemoryRouter>); }
it.each([["/forgot-password", "ForgotPasswordPage"], ["/reset-password", "ResetPasswordPage"], ["/instructor", "InstructorHome"], ["/instructor/my-classes", "MyClasses"], ["/instructor/activity-library", "ActivityLibrary"], ["/instructor/lesson-plans", "LessonPlans"], ["/instructor/attendance", "InstructorPlaceholder"], ["/instructor/print", "PrintPlans"], ["/sign-in", "SignInPage"], ["/account", "AccountPage"], ["/team", "TeamPage"], ["/", "DashboardPage"], ["/manage-sessions", "ManageSessionsPage"], ["/device-exports", "DeviceExportPage"], ["/print", "PrintPage"], ["/rosters", "RostersPage"], ["/schematic", "SchematicPage"], ["/report-cards", "ReportCardsPage"], ["/staff-notes", "StaffNotesPage"], ["/session-planning", "SessionPlanningPage"], ["/requests", "RequestsPage"], ["/full-timer-tools", "FullTimerToolsPage"]])("preserves the %s route", (url, page) => { setup(url); expect(screen.getByText(page)).toBeVisible(); });
it.each(["/requests", "/full-timer-tools"])("requires sign-in for guest access to %s", url => { auth.isGuest = true; setup(url); expect(screen.getByText("SignInPage")).toBeVisible(); });
it.each(["/requests", "/full-timer-tools"])("preserves the full-time gate for %s", url => { auth.accountType = "part_time"; setup(url); expect(screen.getByRole("heading", { name: "Full-time access only" })).toBeVisible(); });
