-- Generated by frontend/scripts/generate-lesson-skills.mjs from Rectab catalog.json.
-- Apply after supabase_lesson_plans.sql and before deploying the updated API.
begin;
alter table public.instructor_plans add column if not exists curriculum_level text;
alter table public.instructor_plans drop constraint if exists instructor_plan_curriculum_level;
alter table public.instructor_plans add constraint instructor_plan_curriculum_level
 check (curriculum_level is null or curriculum_level in ('LittleSplash1', 'LittleSplash2', 'LittleSplash3', 'LittleSplash4', 'LittleSplash5', 'ParentandTot1', 'ParentandTot2', 'ParentandTot3', 'Splash1', 'Splash2A', 'Splash2B', 'Splash3', 'Splash4', 'Splash5', 'Splash6', 'Splash7', 'Splash8', 'Splash9', 'SplashFitness', 'TeenAdult1', 'TeenAdult2', 'TeenAdult3'));
commit;
