export const ATTENDANCE_STAGE_WIDTH = 1056
export const ATTENDANCE_STAGE_HEIGHT = 816
export const ATTENDANCE_CAPTURE_PIXEL_RATIO = 3
export const ATTENDANCE_CAPTURE_WIDTH = ATTENDANCE_STAGE_WIDTH * ATTENDANCE_CAPTURE_PIXEL_RATIO
export const ATTENDANCE_CAPTURE_HEIGHT = ATTENDANCE_STAGE_HEIGHT * ATTENDANCE_CAPTURE_PIXEL_RATIO
export const ATTENDANCE_PRINTABLE_WIDTH = 1009.6
export const ATTENDANCE_PRINTABLE_HEIGHT = 769.6
export function computeAttendanceContentScale(width: number, height: number) {
  if (width <= 0 || height <= 0) return 1
  return Math.min(1, ATTENDANCE_PRINTABLE_WIDTH / width, ATTENDANCE_PRINTABLE_HEIGHT / height)
}
