import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, expect, it, vi } from "vitest";
import { installLocalStorage } from "../../../test/storage";
import { loadFullTimeRequestEntries } from "./fullTimeStorage";
import Rosters from "./Rosters.component";
const state = vi.hoisted(() => ({ currentTeamId: "team", showAppNotice: vi.fn() }));
vi.mock("../../../app/AuthContext", () => ({ useAuth: () => ({ accountType: "full_time", isGuest: true, user: null }) }));
vi.mock("../../../app/DayContext", () => ({ useDay: () => ({ selectedDay: "Mo" }) }));
vi.mock("../../../app/useCurrentSession", () => ({ useCurrentSession: () => ({ access: { mode: "owner" }, sessionId: "", session: null }) }));
vi.mock("../../../app/useCurrentTeam", () => ({ useCurrentTeam: () => ({ currentTeamId: state.currentTeamId, currentTeam: { name: "Aquatics" } }) }));
vi.mock("../../../app/useCurrentTerm", () => ({ useCurrentTerm: () => ({ currentTerm: { key: "fall:2026", label: "Fall 2026" } }) }));
vi.mock("../../../lib/appNotice", () => ({ showAppNotice: state.showAppNotice }));
vi.mock("./hooks/useRosterData", () => ({ useRosterData: () => ({ students: [], rosters: [], instructorOptions: [], setStudents: vi.fn() }) }));
vi.mock("./hooks/useCustomRosters", () => ({ useCustomRosters: () => ({ customRosters: [], saveCustomRosters: vi.fn(), updateCustomRosterLevel: vi.fn() }) }));
beforeEach(() => { installLocalStorage(); window.sessionStorage.clear(); state.currentTeamId = "team"; vi.clearAllMocks(); });
it("requires a team before showing full-time rosters", () => { state.currentTeamId = ""; render(<Rosters />); expect(screen.getByText(/Select a team/)).toBeVisible(); });
it("switches to the request editor, validates fields, and persists a request", async () => {
    const user = userEvent.setup();
    render(<Rosters />);
    await user.click(screen.getByRole("button", { name: "Request List" }));
    await user.click(screen.getByRole("button", { name: "Add Request" }));
    expect(state.showAppNotice).toHaveBeenCalledWith(expect.stringContaining("Enter first name"), "error");
    await user.type(screen.getByPlaceholderText("First name"), "Sam");
    await user.type(screen.getByPlaceholderText("Last name"), "River");
    await user.type(screen.getByPlaceholderText("Phone number"), "5551234567");
    await user.type(screen.getByPlaceholderText("Requested instructor"), "Alex");
    await user.click(screen.getByRole("button", { name: "Add Request" }));
    expect(screen.getAllByDisplayValue("Sam")).toHaveLength(1);
    expect(loadFullTimeRequestEntries("team", "fall:2026")).toEqual([expect.objectContaining({ firstName: "Sam", instructor: "Alex" })]);
});
