import { cleanup,fireEvent,render,screen,waitFor,within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { createMemoryRouter,RouterProvider } from 'react-router-dom'
import {beforeEach,expect,it,vi} from 'vitest'
import {LessonEditor} from './LessonPlans'
import {curriculumLevels} from './lessonSkills'
const api=vi.hoisted(()=>({fetchLessonPlan:vi.fn(),saveLessonPlan:vi.fn()}))
vi.mock('../../lib/serverApi',()=>api)
beforeEach(()=>{api.fetchLessonPlan.mockReset().mockResolvedValue({plan:null});api.saveLessonPlan.mockReset()})
function setup(level="Splash 1"){return render(<RouterProvider router={createMemoryRouter([{path:'/',element:<LessonEditor sessionId="s" classId="c" week="2026-10-05" level={level}/>}])}/>)}
it('keeps untouched plans null and retains drafts on save failure',async()=>{
 const user=userEvent.setup();setup()
 await screen.findByText(/No lesson plan saved/)
 expect(api.saveLessonPlan).not.toHaveBeenCalled()
 await user.click(screen.getByRole('button',{name:'Add activity'}))
 await user.selectOptions(screen.getByLabelText('Skill 1'),'Enter and Exit Shallow Water')
 api.saveLessonPlan.mockRejectedValueOnce(new Error('Offline'))
 await user.click(screen.getByRole('button',{name:'Save'}))
 expect(await screen.findByRole('alert')).toHaveTextContent('Your draft is retained')
 expect(screen.getByLabelText('Skill 1')).toHaveValue('Enter and Exit Shallow Water')
 api.saveLessonPlan.mockImplementation(async(_s,_c,_w,rows)=>({plan:{rows}}))
 await user.click(screen.getByRole('button',{name:'Save'}))
 expect(await screen.findByText('Lesson plan saved.')).toBeVisible()
 expect(screen.queryByText('Unsaved changes')).not.toBeInTheDocument()
})
it('reorders and removes rows before explicit save',async()=>{
 api.fetchLessonPlan.mockResolvedValue({plan:{rows:[{skill:'First',activity:'A',location:'Lane',duration:5},{skill:'Second',activity:'B',location:'Deep end',duration:10}]}})
 const user=userEvent.setup();setup();await screen.findByLabelText('Skill 1')
 screen.getByRole('button',{name:'Reorder row 2'}).focus()
 await user.keyboard('{ArrowUp}')
 expect(screen.getByRole('button',{name:'Reorder row 1'})).toHaveFocus()
 expect(screen.queryByText('Row actions')).not.toBeInTheDocument()
 expect(screen.getByLabelText('Skill 1')).toHaveValue('Second')
 await user.click(screen.getByRole('button',{name:'Delete row 2'}))
 api.saveLessonPlan.mockImplementation(async(_s,_c,_w,rows)=>({plan:{rows}}))
 await user.click(screen.getByRole('button',{name:'Save'}))
 await waitFor(()=>expect(api.saveLessonPlan).toHaveBeenCalledWith('s','c','2026-10-05',[{skill:'Second',activity:'B',location:'Deep end',duration:10}],null))
})
it('offers only the class level skills in catalog order',async()=>{
 const user=userEvent.setup();setup('Splash 2A')
 await screen.findByText(/No lesson plan saved/)
 await user.click(screen.getByRole('button',{name:'Add activity'}))
 const select=screen.getByRole('combobox',{name:'Skill 1'})
 expect(within(select).getAllByRole('option').map(option=>option.textContent)).toEqual(['Select skill',...curriculumLevels.find(l=>l.id==='Splash2A')!.skills.map(s=>s.compactName)])
 expect(screen.queryByLabelText('Curriculum level')).not.toBeInTheDocument()
})
it('requires a plan level for private classes, preserves rows on changes, and restores the saved level',async()=>{
 const user=userEvent.setup()
 api.fetchLessonPlan.mockResolvedValue({plan:{curriculum_level:'Splash1',rows:[{skill:'Enter and Exit Shallow Water',activity:'Practice',location:'Lane',duration:5}]}})
 const view=setup('Splash Private')
 expect(await screen.findByLabelText('Curriculum level')).toHaveValue('Splash1')
 await user.selectOptions(screen.getByLabelText('Curriculum level'),'Splash2A')
 expect(screen.getByText('Unsaved changes')).toBeVisible()
 expect(screen.getByLabelText('Skill 1')).toHaveValue('Enter and Exit Shallow Water')
 expect(screen.getByLabelText('Activity / drill 1')).toHaveValue('Practice')
 const skill=curriculumLevels.find(l=>l.id==='Splash2A')!.skills[0].name
 await user.selectOptions(screen.getByLabelText('Skill 1'),skill)
 const plan={curriculum_level:'Splash2A',rows:[{skill,activity:'Practice',location:'Lane',duration:5}]}
 api.saveLessonPlan.mockResolvedValue({plan})
 await user.click(screen.getByRole('button',{name:'Save'}))
 await screen.findByText('Lesson plan saved.')
 expect(api.saveLessonPlan).toHaveBeenCalledWith('s','c','2026-10-05',plan.rows,'Splash2A')
 expect(screen.queryByText('Unsaved changes')).not.toBeInTheDocument()
 view.unmount();api.fetchLessonPlan.mockResolvedValue({plan});setup('Splash Private')
 expect(await screen.findByLabelText('Curriculum level')).toHaveValue('Splash2A')
 expect(screen.getByLabelText('Skill 1')).toHaveValue(skill)
})
it.each(['Splash Private','Unknown level',''])('waits for curriculum choice for %s and retains a level-only draft after save failure',async level=>{
 const user=userEvent.setup();setup(level)
 await screen.findByText(/No lesson plan saved/)
 await user.click(screen.getByRole('button',{name:'Add activity'}))
 expect(screen.getByLabelText('Skill 1')).toBeDisabled()
 const levels=within(screen.getByLabelText('Curriculum level')).getAllByRole('option')
 expect(levels.map(l=>(l as HTMLOptionElement).value)).not.toContain('SplashPrivate')
 await user.selectOptions(screen.getByLabelText('Curriculum level'),'LittleSplash1')
 expect(screen.getByLabelText('Skill 1')).toBeEnabled()
 await user.click(screen.getByRole('button',{name:'Delete row 1'}))
 api.saveLessonPlan.mockRejectedValueOnce(new Error('Offline'))
 await user.click(screen.getByRole('button',{name:'Save'}))
 expect(await screen.findByRole('alert')).toHaveTextContent('Your draft is retained')
 expect(screen.getByLabelText('Curriculum level')).toHaveValue('LittleSplash1')
 expect(screen.getByText('Unsaved changes')).toBeVisible()
})
it('guards navigation when only the private curriculum level has changed',async()=>{
 const user=userEvent.setup()
 const router=createMemoryRouter([{path:'/',element:<LessonEditor sessionId="s" classId="c" week="2026-10-05" level="Splash Private"/>},{path:'/away',element:<p>Another page</p>}])
 render(<RouterProvider router={router}/>)
 await screen.findByLabelText('Curriculum level')
 await user.selectOptions(screen.getByLabelText('Curriculum level'),'Splash1')
 const confirm=vi.spyOn(window,'confirm').mockReturnValue(false)
 try {
  await router.navigate('/away')
  await waitFor(()=>expect(confirm).toHaveBeenCalledWith('Discard unsaved lesson plan changes?'))
  expect(screen.getByLabelText('Curriculum level')).toHaveValue('Splash1')
  confirm.mockReturnValue(true)
  await router.navigate('/away')
  expect(await screen.findByText('Another page')).toBeVisible()
 } finally {confirm.mockRestore()}
})

it('drags rows to a new position using the left handle',async()=>{
 api.fetchLessonPlan.mockResolvedValue({plan:{rows:[{skill:'First',activity:'A',location:'Lane',duration:5},{skill:'Second',activity:'B',location:'Deep end',duration:10}]}})
 setup();await screen.findByLabelText('Skill 1')
 const handle=screen.getByRole('button',{name:'Reorder row 1'})
 handle.setPointerCapture=vi.fn()
 handle.releasePointerCapture=vi.fn()
 vi.stubGlobal('PointerEvent',MouseEvent)
 const elementFromPoint=vi.fn().mockReturnValue(screen.getByLabelText('Skill 2'))
 const originalElementFromPoint=document.elementFromPoint
 document.elementFromPoint=elementFromPoint
 try {
  fireEvent.pointerDown(handle,{button:0})
  fireEvent.pointerMove(handle,{clientX:50,clientY:200})
  fireEvent.pointerUp(handle,{clientX:50,clientY:200})
  expect(screen.getByLabelText('Skill 1')).toHaveValue('Second')
  expect(screen.getByLabelText('Activity / drill 2')).toHaveValue('A')
  expect(screen.getByText('Unsaved changes')).toBeVisible()
  expect(api.saveLessonPlan).not.toHaveBeenCalled()
 } finally {document.elementFromPoint=originalElementFromPoint;vi.unstubAllGlobals()}
})

function mockLibraryDialog() {
 const prototype=HTMLDialogElement.prototype
 const originals=['showModal','close'].map(name=>Object.getOwnPropertyDescriptor(prototype,name))
 Object.defineProperty(prototype,'showModal',{configurable:true,value:function(this:HTMLDialogElement){this.setAttribute('open','');this.querySelector<HTMLButtonElement>('button')?.focus()}})
 Object.defineProperty(prototype,'close',{configurable:true,value:function(this:HTMLDialogElement){this.removeAttribute('open')}})
 return ()=>{cleanup();['showModal','close'].forEach((name,i)=>{const original=originals[i];if(original)Object.defineProperty(prototype,name,original);else Reflect.deleteProperty(prototype,name)})}
}
it('inserts from the library without changing other row fields and persists only on save',async()=>{
 const restore=mockLibraryDialog()
 const skill=curriculumLevels.find(l=>l.id==='Splash1')!.skills.find(s=>s.id==='Splash1:5')!
 const original=[{skill:skill.name,activity:'',location:'Deep end',duration:12},{skill:'Other saved skill',activity:'Keep this',location:'Lane',duration:3}]
 api.fetchLessonPlan.mockResolvedValue({plan:{rows:original}})
 api.saveLessonPlan.mockImplementation(async(_s,_c,_w,rows)=>({plan:{rows}}))
 const user=userEvent.setup();const view=setup()
 try {
  const trigger=await screen.findByRole('button',{name:'Browse library for row 1'})
  await user.click(trigger)
  const dialog=screen.getByRole('dialog',{name:'Activity Library'})
  await user.click(within(dialog).getByRole('checkbox',{name:'Only activities for Submerge & exhale ×5'}))
  await user.type(within(dialog).getByRole('searchbox'),'Five Little Ducks')
  await user.click(within(dialog).getByText('Five Little Ducks'))
  await user.click(within(dialog).getByRole('button',{name:'Use Five Little Ducks'}))
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  expect(trigger).toHaveFocus()
  const inserted=(screen.getByLabelText('Activity / drill 1') as HTMLTextAreaElement).value
  expect(inserted).toContain('Five Little Ducks')
  expect(inserted).toContain('blow bubbles')
  expect(screen.getByLabelText('Skill 1')).toHaveValue(skill.name)
  expect(screen.getByLabelText('Pool location 1')).toHaveValue('Deep end')
  expect(screen.getByLabelText('Duration (minutes) 1')).toHaveValue(12)
  expect(screen.getByLabelText('Activity / drill 2')).toHaveValue('Keep this')
  expect(screen.getByText('Unsaved changes')).toBeVisible()
  expect(api.saveLessonPlan).not.toHaveBeenCalled()
  await user.click(screen.getByRole('button',{name:'Save'}))
  await screen.findByText('Lesson plan saved.')
  const expected=[{...original[0],activity:inserted},original[1]]
  expect(api.saveLessonPlan).toHaveBeenCalledWith('s','c','2026-10-05',expected,null)
  view.unmount();api.fetchLessonPlan.mockResolvedValue({plan:{rows:expected}});setup()
  expect(await screen.findByLabelText('Activity / drill 1')).toHaveValue(inserted)
 } finally {restore()}
})
it('confirms replacement and preserves the draft and picker when replacement is cancelled',async()=>{
 const restore=mockLibraryDialog()
 const confirm=vi.spyOn(window,'confirm').mockReturnValue(false)
 api.fetchLessonPlan.mockResolvedValue({plan:{rows:[{skill:'Unknown saved skill',activity:'My own instructions',location:'Lane',duration:5}]}})
 const user=userEvent.setup();setup()
 try {
  await user.click(await screen.findByRole('button',{name:'Browse library for row 1'}))
  const dialog=screen.getByRole('dialog')
  expect(within(dialog).getByRole('checkbox')).toBeDisabled()
  await user.type(within(dialog).getByRole('searchbox'),'Chop, Chop, Timber')
  await user.click(within(dialog).getByText('Chop, Chop, Timber'))
  await user.click(within(dialog).getByRole('button',{name:'Use Chop, Chop, Timber'}))
  expect(confirm).toHaveBeenCalledWith('Replace this row’s activity text with the selected library activity?')
  expect(screen.getByLabelText('Activity / drill 1')).toHaveValue('My own instructions')
  expect(dialog).toBeVisible()
  confirm.mockReturnValue(true)
  await user.click(within(dialog).getByRole('button',{name:'Use Chop, Chop, Timber'}))
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  expect(screen.getByLabelText('Activity / drill 1')).not.toHaveValue('My own instructions')
  expect(api.saveLessonPlan).not.toHaveBeenCalled()
 } finally {restore();confirm.mockRestore()}
})
it('closes the library with the close button or Escape without dirtying the plan',async()=>{
 const restore=mockLibraryDialog()
 api.fetchLessonPlan.mockResolvedValue({plan:{rows:[{skill:'',activity:'',location:'Lane',duration:5}]}})
 const user=userEvent.setup();setup()
 try {
  const trigger=await screen.findByRole('button',{name:'Browse library for row 1'})
  await user.click(trigger)
  expect(screen.getByRole('checkbox')).toBeDisabled()
  await user.click(screen.getByRole('button',{name:'Close activity library'}))
  expect(trigger).toHaveFocus()
  await user.click(trigger)
  fireEvent(screen.getByRole('dialog'),new Event('cancel',{cancelable:true}))
  expect(screen.queryByRole('dialog')).not.toBeInTheDocument()
  expect(trigger).toHaveFocus()
  expect(screen.queryByText('Unsaved changes')).not.toBeInTheDocument()
  expect(screen.getByLabelText('Activity / drill 1')).toHaveValue('')
 } finally {restore()}
})

it('builds, saves, reopens and converts a structured workout while preserving row fields',async()=>{
 const restore=mockLibraryDialog();const confirm=vi.spyOn(window,'confirm').mockReturnValue(false)
 try {
  api.fetchLessonPlan.mockResolvedValue({plan:{rows:[{skill:'Float',activity:'Original text',location:'Deep end',duration:12}]}})
  api.saveLessonPlan.mockImplementation(async(_s,_c,_w,rows)=>({plan:{rows}}))
  const user=userEvent.setup();setup();await screen.findByLabelText('Skill 1')
  await user.click(screen.getByRole('button',{name:'Build workout for row 1'}))
  const dialog=screen.getByRole('dialog',{name:'Workout builder'})
  await user.click(within(dialog).getByRole('button',{name:'Use workout'}))
  expect(within(dialog).getByRole('alert')).toHaveTextContent('warm-up')
  await user.selectOptions(within(dialog).getByLabelText('Choose warm-up preset'),'young-1-warm')
  await user.selectOptions(within(dialog).getByLabelText('Choose main set preset'),'young-1-main')
  await user.click(within(dialog).getByRole('button',{name:'Create custom cool-down'}))
  await user.click(within(dialog).getByRole('button',{name:'Add cool-down set'}))
  await user.clear(within(dialog).getByLabelText('Cool-down set 2 distance'))
  await user.type(within(dialog).getByLabelText('Cool-down set 2 distance'),'50')
  await user.click(within(dialog).getByRole('button',{name:'Move Cool-down set 2 up'}))
  expect(within(dialog).getByLabelText('Cool-down set 1 distance')).toHaveValue(50)
  await user.click(within(dialog).getByRole('button',{name:'Delete Cool-down set 2'}))
  await user.click(within(dialog).getByRole('button',{name:'Use workout'}))
  expect(confirm).toHaveBeenCalledWith('Replace this row’s activity text with the workout?')
  expect(screen.getByLabelText('Activity / drill 1')).toHaveValue('Original text')
  confirm.mockReturnValue(true)
  await user.click(within(dialog).getByRole('button',{name:'Use workout'}))
  const summary=screen.getByLabelText('Workout summary 1').textContent
  expect(summary).toContain('Total distance: 400 m')
  await user.click(screen.getByRole('button',{name:'Save'}))
  await screen.findByText('Lesson plan saved.')
  const rows=api.saveLessonPlan.mock.calls[0][3]
  expect(rows[0]).toMatchObject({skill:'Float',location:'Deep end',duration:12,workout:{version:1}})
  await user.click(screen.getByRole('button',{name:'Edit workout for row 1'}))
  await user.clear(screen.getByLabelText('Workout title'))
  await user.type(screen.getByLabelText('Workout title'),'Changed')
  confirm.mockReturnValue(false)
  await user.click(screen.getByRole('button',{name:'Close workout builder'}))
  expect(screen.getByRole('dialog')).toBeVisible()
  confirm.mockReturnValue(true)
  await user.click(screen.getByRole('button',{name:'Close workout builder'}))
  expect(screen.getByLabelText('Workout summary 1').textContent).toBe(summary)
  confirm.mockReturnValue(false)
  await user.click(screen.getByRole('button',{name:'Convert workout in row 1 to text'}))
  expect(screen.getByLabelText('Workout summary 1')).toBeVisible()
  confirm.mockReturnValue(true)
  await user.click(screen.getByRole('button',{name:'Convert workout in row 1 to text'}))
  expect(screen.getByLabelText('Activity / drill 1')).toHaveValue(summary)
  await user.click(screen.getByRole('button',{name:'Save'}))
  await waitFor(()=>expect(api.saveLessonPlan).toHaveBeenCalledTimes(2))
  expect(api.saveLessonPlan.mock.calls[1][3][0].workout).toBeUndefined()
 } finally {confirm.mockRestore();restore()}
})
